version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  backend:
    build: ./backend
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - ./backend:/app
  
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'
  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
    volumes:
      - es_data:/usr/share/elasticsearch/data/

volumes:
  postgres_data:
  es_data: