version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  frontend:
    build: ./frontend
    restart: always
    ports:
      - '5173:5173'
    volumes:
      - /app/node_modules
      - ./frontend:/app
  backend:
    build: ./backend
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - ./backend:/app
  
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'

volumes:
  postgres_data: