# Generated by Django 5.1.4 on 2025-03-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('carrier_rates', models.BooleanField(default=True)),
                ('free_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_time', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Тариф доставки',
                'verbose_name_plural': 'Тарифи доставки',
                'db_table': 'DeliveryOption',
            },
        ),
    ]
