# Generated by Django 5.1.4 on 2025-01-19 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_price', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('online_card', 'Online Payment (Card)'), ('google_pay', 'Google Pay')], default='cod', max_length=30, verbose_name='Спосіб оплати')),
                ('delivery_address', models.TextField(max_length=150)),
                ('delivery_type', models.CharField(choices=[('nova_poshta', 'Nova Poshta'), ('ukr_poshta', 'Ukrposhta')], default='nova_poshta', max_length=20, verbose_name='Метод доставки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
    ]
