# Generated by Django 5.1.4 on 2025-03-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryoption',
            name='carrier_rates',
        ),
        migrations.RemoveField(
            model_name='deliveryoption',
            name='estimated_time',
        ),
    ]
