# Generated by Django 5.1.4 on 2025-01-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type_en',
            field=models.CharField(choices=[('nova_poshta', 'Nova Poshta'), ('ukr_poshta', 'Ukrposhta')], default='nova_poshta', max_length=20, null=True, verbose_name='Метод доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type_uk',
            field=models.CharField(choices=[('nova_poshta', 'Nova Poshta'), ('ukr_poshta', 'Ukrposhta')], default='nova_poshta', max_length=20, null=True, verbose_name='Метод доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method_en',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online_card', 'Online Payment (Card)'), ('google_pay', 'Google Pay')], default='cod', max_length=30, null=True, verbose_name='Спосіб оплати'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method_uk',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online_card', 'Online Payment (Card)'), ('google_pay', 'Google Pay')], default='cod', max_length=30, null=True, verbose_name='Спосіб оплати'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_en',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_uk',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
