# Generated by Django 5.1.4 on 2025-01-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_type_en_order_delivery_type_uk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AlterModelTable(
            name='order',
            table='Orders',
        ),
    ]
