# Generated by Django 5.1.4 on 2025-03-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_deliveryoption_carrier_rates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoption',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
