# Generated by Django 5.1.4 on 2025-03-04 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата останнього оновлення')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Сесія')),
                ('last_accessed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Останній вхід')),
            ],
            options={
                'verbose_name': 'Кошик',
                'verbose_name_plural': 'Кошики',
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість товару')),
                ('price', models.FloatField(default=0, editable=False, verbose_name='Ціна товару')),
            ],
            options={
                'verbose_name': 'Товар в кошику',
                'verbose_name_plural': 'Товари в кошику',
                'db_table': 'CartItem',
            },
        ),
    ]
