# Generated by Django 5.1.4 on 2025-01-12 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_session_id_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='last_accesed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
