# Generated by Django 5.1.4 on 2025-01-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_last_accesed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='last_accesed',
            new_name='last_accessed',
        ),
    ]
