# Generated by Django 5.1.4 on 2025-01-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_rename_last_accesed_cart_last_accessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(default=0, editable=False, verbose_name='Ціна товару'),
        ),
    ]
