# Generated by Django 5.1.4 on 2025-03-02 19:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cartitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='last_accessed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Останній вхід'),
        ),
    ]
