# Generated by Django 5.1.4 on 2025-01-02 08:03

import phonenumber_field.modelfields
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Електронна адреса')),
                ('name', models.CharField(max_length=30, verbose_name="Ім'я")),
                ('surname', models.CharField(blank=True, max_length=30, verbose_name='Прізвище')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефону')),
                ('address', models.TextField(blank=True, max_length=200, verbose_name='Адреса доставки')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=user.models.user_directory_path, validators=[user.models.validate_image], verbose_name='Фото профілю')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Останній вхід')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Адміністратор')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
                'db_table': 'User',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='User_email_ffa2e0_idx'), models.Index(fields=['name'], name='User_name_ad0720_idx')],
            },
        ),
    ]
