# Generated by Django 5.1.4 on 2024-12-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='User_first_n_22d48d_idx',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='surname',
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['name'], name='User_name_ad0720_idx'),
        ),
    ]
