# Generated by Django 5.1.4 on 2025-03-12 13:36

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to=user.models.user_directory_path, validators=[user.models.validate_image], verbose_name='Фото профілю'),
        ),
    ]
