# Generated by Django 5.1.4 on 2025-03-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='varranty',
            field=models.PositiveIntegerField(default=0, verbose_name='Гарантія'),
        ),
    ]
