# Generated by Django 5.1.4 on 2025-03-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_varranty_product_warranty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.PositiveIntegerField(default=0, help_text='Введіть ціну з урахуванням знижки', verbose_name='Знижка'),
        ),
    ]
