# Generated by Django 5.1.4 on 2025-04-02 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_discount_product_discounted_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_filterable', models.BooleanField(default=True, verbose_name='Доступний для фільтрів')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attribute', verbose_name='Атрибут')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Атрибут категорії',
                'verbose_name_plural': 'Атрибути категорій',
                'unique_together': {('category', 'attribute')},
            },
        ),
    ]
