# Generated by Django 5.1.4 on 2024-12-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_name_en_category_name_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва атрибуту'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва атрибуту'),
        ),
    ]
