# Generated by Django 5.1.4 on 2025-03-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productcomment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productcomment',
            table='ProductComment',
        ),
    ]
