# Generated by Django 5.1.4 on 2025-04-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_categoryattribute'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryattribute',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='categoryattribute',
            table='CategoryAttribute',
        ),
        migrations.RemoveField(
            model_name='categoryattribute',
            name='category',
        ),
        migrations.AddField(
            model_name='categoryattribute',
            name='category',
            field=models.ManyToManyField(related_name='attributes', to='product.category', verbose_name='Категорія'),
        ),
    ]
