# Generated by Django 5.1.4 on 2024-12-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='category_images/', verbose_name='Фото товару'),
        ),
    ]
