# Generated by Django 5.1.4 on 2025-01-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_category_is_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_parent',
        ),
    ]
