# Generated by Django 5.1.4 on 2025-01-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_category_is_parent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attribute',
            name='Attribute_categor_8d5c9c_idx',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='category',
        ),
    ]
