# Generated by Django 5.1.4 on 2025-01-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
