# Generated by Django 5.1.4 on 2025-01-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
