# Generated by Django 5.1.4 on 2025-01-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_rename_categories_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
