# Generated by Django 5.1.4 on 2025-03-02 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_category_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
