# Generated by Django 5.1.4 on 2025-03-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='', upload_to='news_images/%Y/%m/%d/', verbose_name='Фото новини'),
            preserve_default=False,
        ),
    ]
