# Generated by Django 5.1.4 on 2025-02-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publish'], 'verbose_name': 'Новини', 'verbose_name_plural': 'Новина'},
        ),
    ]
