# Generated by Django 5.1.4 on 2025-03-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_uk', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('description_en', models.TextField(null=True, verbose_name='Опис')),
                ('description_uk', models.TextField(null=True, verbose_name='Опис')),
                ('image', models.ImageField(upload_to='banner_img/', verbose_name='Фото банера')),
            ],
            options={
                'verbose_name': 'Банер',
                'verbose_name_plural': 'Банери',
                'db_table': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва компанії партнера')),
                ('image', models.ImageField(upload_to='partners/', verbose_name='Логотип компанії партнера')),
            ],
            options={
                'verbose_name': 'Логотип партнера',
                'verbose_name_plural': 'Логотипи партнерів',
                'db_table': 'Partner',
            },
        ),
    ]
