# Generated by Django 5.1.4 on 2025-01-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='partners/', verbose_name='Логотип партнера')),
            ],
            options={
                'verbose_name': 'Логотип партнера',
                'verbose_name_plural': 'Логотипи партнерів',
                'db_table': 'Partner',
            },
        ),
    ]
