# Generated by Django 5.1.4 on 2025-03-13 12:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_review'),
        ('product', '0003_product_delivery_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сесія')),
                ('last_accessed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Останній вхід')),
                ('products', models.ManyToManyField(related_name='wishlists', to='product.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Список бажаного',
                'verbose_name_plural': 'Списки бажаного',
                'db_table': 'Wishlist',
            },
        ),
    ]
