# Generated by Django 5.1.4 on 2025-03-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_wishlist_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wishlist',
            table='Wishlist',
        ),
        migrations.AlterModelTable(
            name='wishlistitem',
            table='WishlistItem',
        ),
    ]
